services:
  api:
    image: fastapi # Oluşturduğun imajı kullanmaya devam ediyoruz.
    container_name: hizmetypinari_fastapi_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    # KESİN ÇÖZÜM: Hatalı 'unicorn' komutunu ezip doğru komutu çalıştırmayı garanti ediyoruz.
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      DATABASE_HOSTNAME: db
      DATABASE_PORT: 3306
      DATABASE_PASSWORD: password
      DATABASE_NAME: hizmetypinari_db
      DATABASE_USERNAME: user
    networks:
      - net1
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: hizmetypinari_mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hizmetypinari_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - net1
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: hizmetypinari_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    networks:
      - net1
    depends_on:
      db:
        condition: service_healthy

networks:
  net1:
    driver: bridge

volumes:
  mysql_data:

